FROM node:22-alpine
WORKDIR /app
COPY package*.json tsconfig.json tsconfig.base.json ./
COPY src ./src
RUN npm install
EXPOSE 3000
CMD ["npx", "ts-node-dev", "--respawn", "--transpile-only", "src/index.ts"]
