repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: runix
    url: https://helm.runix.net
  - name: ectobit
    url: https://charts.ectobit.com
  - name: hasura
    url: https://hasura.github.io/helm-charts

---

releases:

  - name: postgres
    chart: bitnami/postgresql
    namespace: default
    values:
      - values/postgres/common.yaml

  - name: pgweb
    chart: ectobit/pgweb
    values:
      - values/pgweb/common.yaml

  - name: frontend
    chart: ../charts/frontend
    values:
      - values/frontend/common.yaml
    namespace: default

  - name: backend
    chart: ../charts/backend
    values:
      - values/backend/common.yaml
    namespace: default

  - name: ingress
    chart: ./templates/ingress
    values:
      - ./templates/ingress/values.yaml
    namespace: default

  - name: hasura
    chart: ../charts/hasura
    namespace: default
    values:
      - values/hasura/common.yaml
